import Foundation

/// A writer for generated `.strings` files.
public enum StringsWriter {
    public static let header = """
        // Generated by LocalizableMerger. Do not edit this file.
        // Edit the source .strings files, then run localizable-merger again.
        """

    /// Returns the text of a generated file. The entries are in key order.
    public static func render(_ entries: [String: String]) -> String {
        var text = header + "\n\n"
        for (key, value) in entries.sorted(by: { $0.key < $1.key }) {
            text += "\"\(escape(key))\" = \"\(escape(value))\";\n"
        }
        return text
    }

    public static func escape(_ text: String) -> String {
        var result = ""
        for character in text.unicodeScalars {
            switch character {
            case "\"": result += "\\\""
            case "\\": result += "\\\\"
            case "\n": result += "\\n"
            case "\t": result += "\\t"
            case "\r": result += "\\r"
            default: result.unicodeScalars.append(character)
            }
        }
        return result
    }

    /// Writes UTF-8 text to a file when the content of the file is different.
    ///
    /// - Returns: `true` when the function wrote the file.
    @discardableResult
    public static func write(_ text: String, to url: URL) throws -> Bool {
        let data = Data(text.utf8)
        if (try? Data(contentsOf: url)) == data { return false }
        do {
            try data.write(to: url, options: .atomic)
        } catch {
            throw MergerError.writeFailed(path: url.path, reason: error.localizedDescription)
        }
        return true
    }
}
