import Foundation
import Testing
@testable import LocalizableMergerCore

@Suite struct StringsWriterTests {
    @Test func rendersTheHeaderAndTheEntriesInKeyOrder() {
        let text = StringsWriter.render(["b": "2", "a": "1", "c": "3"])
        #expect(text == StringsWriter.header + "\n\n\"a\" = \"1\";\n\"b\" = \"2\";\n\"c\" = \"3\";\n")
        #expect(text.hasPrefix("// Generated by LocalizableMerger. Do not edit this file.\n"))
    }

    @Test func escapesSpecialCharacters() {
        #expect(StringsWriter.escape("a\"b") == #"a\"b"#)
        #expect(StringsWriter.escape("a\\b") == #"a\\b"#)
        #expect(StringsWriter.escape("a\nb\tc\rd") == #"a\nb\tc\rd"#)
        #expect(StringsWriter.render(["k\"": "\\n"]).hasSuffix("\"k\\\"\" = \"\\\\n\";\n"))
    }

    @Test(arguments: [
        [:],
        ["plain": "value"],
        ["quote\"key": "say \"hello\"", "path": "C:\\dir\\new", "multi": "one\ntwo\r\nthree\tend"],
        ["unicode": "aplicación 😀 日本語", "comment": "// not /* a */ comment", "format": "%1$@ of %2$d; 100%"],
        ["": "", "trailing\\": "\\", " spaces ": "  "],
    ])
    func parsesItsOwnOutput(entries: [String: String]) throws {
        let table = try StringsParser.parse(StringsWriter.render(entries))
        #expect(table.entries == entries)
        #expect(table.duplicateKeys.isEmpty)
    }

    @Test func writesOnlyWhenTheContentIsDifferent() throws {
        let directory = try TempDirectory()
        let url = directory.file("out.strings")
        #expect(try StringsWriter.write("one", to: url))

        let old = Date(timeIntervalSince1970: 1_000_000)
        try FileManager.default.setAttributes([.modificationDate: old], ofItemAtPath: url.path)
        #expect(try StringsWriter.write("one", to: url) == false)
        let date = try FileManager.default.attributesOfItem(atPath: url.path)[.modificationDate] as? Date
        #expect(date == old)

        #expect(try StringsWriter.write("two", to: url))
        #expect(try String(contentsOf: url, encoding: .utf8) == "two")
    }

    @Test func writesUTF8() throws {
        let directory = try TempDirectory()
        let url = directory.file("out.strings")
        try StringsWriter.write(StringsWriter.render(["k": "ñ"]), to: url)
        #expect(try Data(contentsOf: url) == Data((StringsWriter.header + "\n\n\"k\" = \"ñ\";\n").utf8))
    }

    @Test func reportsAWriteFailure() throws {
        let directory = try TempDirectory()
        #expect {
            try StringsWriter.write("x", to: directory.file("absent-folder/out.strings"))
        } throws: { error in
            if case MergerError.writeFailed = error { true } else { false }
        }
    }
}
